// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoComercial.Data;

#nullable disable

namespace ProjetoComercial.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251129172009_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("ProjetoComercial.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoProduto")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("ProjetoComercial.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodigoProduto")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estoque")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoProduto = 101,
                            DescricaoProduto = "Caneta Azul",
                            Estoque = 150
                        },
                        new
                        {
                            Id = 2,
                            CodigoProduto = 102,
                            DescricaoProduto = "Caderno Universitário",
                            Estoque = 75
                        },
                        new
                        {
                            Id = 3,
                            CodigoProduto = 103,
                            DescricaoProduto = "Borracha Branca",
                            Estoque = 200
                        },
                        new
                        {
                            Id = 4,
                            CodigoProduto = 104,
                            DescricaoProduto = "Lápis Preto HB",
                            Estoque = 320
                        },
                        new
                        {
                            Id = 5,
                            CodigoProduto = 105,
                            DescricaoProduto = "Marcador de Texto Amarelo",
                            Estoque = 90
                        });
                });

            modelBuilder.Entity("ProjetoComercial.Models.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendedor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vendas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Valor = 1200.50m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 2,
                            Valor = 950.75m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 3,
                            Valor = 1800.00m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 4,
                            Valor = 1400.30m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 5,
                            Valor = 1100.90m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 6,
                            Valor = 1550.00m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 7,
                            Valor = 1700.80m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 8,
                            Valor = 250.30m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 9,
                            Valor = 480.75m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 10,
                            Valor = 320.40m,
                            Vendedor = "João Silva"
                        },
                        new
                        {
                            Id = 11,
                            Valor = 2100.40m,
                            Vendedor = "Maria Souza"
                        },
                        new
                        {
                            Id = 12,
                            Valor = 1350.60m,
                            Vendedor = "Maria Souza"
                        },
                        new
                        {
                            Id = 13,
                            Valor = 950.20m,
                            Vendedor = "Maria Souza"
                        },
                        new
                        {
                            Id = 14,
                            Valor = 1600.75m,
                            Vendedor = "Maria Souza"
                        },
                        new
                        {
                            Id = 15,
                            Valor = 1750.00m,
                            Vendedor = "Maria Souza"
                        },
                        new
                        {
                            Id = 16,
                            Valor = 1450.90m,
                            Vendedor = "Maria Souza"
                        },
                        new
                        {
                            Id = 17,
                            Valor = 400.50m,
                            Vendedor = "Maria Souza"
                        },
                        new
                        {
                            Id = 18,
                            Valor = 180.20m,
                            Vendedor = "Maria Souza"
                        },
                        new
                        {
                            Id = 19,
                            Valor = 90.75m,
                            Vendedor = "Maria Souza"
                        },
                        new
                        {
                            Id = 20,
                            Valor = 800.50m,
                            Vendedor = "Carlos Oliveira"
                        },
                        new
                        {
                            Id = 21,
                            Valor = 1200.00m,
                            Vendedor = "Carlos Oliveira"
                        },
                        new
                        {
                            Id = 22,
                            Valor = 1950.30m,
                            Vendedor = "Carlos Oliveira"
                        },
                        new
                        {
                            Id = 23,
                            Valor = 1750.80m,
                            Vendedor = "Carlos Oliveira"
                        },
                        new
                        {
                            Id = 24,
                            Valor = 1300.60m,
                            Vendedor = "Carlos Oliveira"
                        },
                        new
                        {
                            Id = 25,
                            Valor = 300.40m,
                            Vendedor = "Carlos Oliveira"
                        },
                        new
                        {
                            Id = 26,
                            Valor = 500.00m,
                            Vendedor = "Carlos Oliveira"
                        },
                        new
                        {
                            Id = 27,
                            Valor = 125.75m,
                            Vendedor = "Carlos Oliveira"
                        },
                        new
                        {
                            Id = 28,
                            Valor = 1000.00m,
                            Vendedor = "Ana Lima"
                        },
                        new
                        {
                            Id = 29,
                            Valor = 1100.50m,
                            Vendedor = "Ana Lima"
                        },
                        new
                        {
                            Id = 30,
                            Valor = 1250.75m,
                            Vendedor = "Ana Lima"
                        },
                        new
                        {
                            Id = 31,
                            Valor = 1400.20m,
                            Vendedor = "Ana Lima"
                        },
                        new
                        {
                            Id = 32,
                            Valor = 1550.90m,
                            Vendedor = "Ana Lima"
                        },
                        new
                        {
                            Id = 33,
                            Valor = 1650.00m,
                            Vendedor = "Ana Lima"
                        },
                        new
                        {
                            Id = 34,
                            Valor = 75.30m,
                            Vendedor = "Ana Lima"
                        },
                        new
                        {
                            Id = 35,
                            Valor = 420.90m,
                            Vendedor = "Ana Lima"
                        },
                        new
                        {
                            Id = 36,
                            Valor = 315.40m,
                            Vendedor = "Ana Lima"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
